[tools]
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"vfox:mise-plugins/vfox-lua" = "5.5"

[tasks.fmt]
description = "Format Lua scripts"
run = "stylua ."

[tasks.lint]
description = "Lint Lua scripts"
run = "lua-language-server --check ."
